server:
  port: 11111 #端口号
spring:
  application:
    name: api-gateway #应用程序名称
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5673
eureka:
  client:
    service-url:
      #Eureka服务地址,如果是集群的话,需要指定其他集群Eureka服务地址
      defaultZone: ${defaultZone:http://localhost:8001/eureka}
    #是否注册到Eureka注册中心
    register-with-eureka: true
    #是否拉去Eureka注册中心服务
    fetch-registry: true
  instance:
    #更倾向于使用IP地址,而不是域名
    prefer-ip-address: true
    #IP地址
    ip-address: 127.0.0.1
    #服务续约时间,默认值30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效时间,默认值90秒
    lease-expiration-duration-in-seconds: 90
#自定义路由映射规则
#http://localhost:11111/order-service/order/save?userId=123&productId=2
#http://localhost:11111/apigateway/order/save?userId=123&productId=2
#zuul:
#  routes:
#    order-service: /apigateway/order/**
#    product-service: /apigateway/product/**
#  #统一入口为上面的配置,其他入口忽略
#  ignored-patterns: /*-service/**
#  #忽略整个服务,对外暴露接口
#  ignored-services: product-service
zuul:
  prefix: /api #路由前缀
  routes:
    order-service: # 这里是路由id,随意写
      path: /order/** # 这里是映射路径
      serviceId: order-service # 指定服务名称
      stripPrefix: false #是否去除路由前缀
  sensitive-headers: #配置禁止使用头信息,这里设置为null,否则设置set-cookie无效
management:
  endpoints:
    web:
      exposure:
        include: "*"
