spring:
  application:
    name: order-service #应用程序名称
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  #ZipKin服务所在地址
  zipkin:
    base-url: http://117.78.17.127:9411/
  #配置采样百分比,开发环境可以设置成1,表示全部;生产环境就用默认的
  sleuth:
    sampler:
      probability: 1.0
server:
  port: ${port:10001} #端口号
eureka:
  #Eureka客户端配置
  client:
    service-url:
      #Eureka服务地址,如果是集群的话,需要指定其他集群Eureka服务地址
      defaultZone: ${defaultZone:http://localhost:8001/eureka}
    #拉取服务列表
    fetch-registry: true
    #是否注册到Eureka
    register-with-eureka: true
  #Eureka实例配置
  instance:
    #更倾向于使用IP地址
    prefer-ip-address: true
    #IP地址
    ip-address: 127.0.0.1
    #服务续约时间,默认值30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效时间,默认值90秒
    lease-expiration-duration-in-seconds: 90
#自定义负载均衡策略,默认是采用轮询
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#修改Feign超时时长,由于hystrix默认是1秒超时
feign:
  hystrix:
    #开启feign支持hystrix
    enabled: true
  client:
    config:
      default:
        #连接超时时长
        connectTimeout: 2000
        #读取数据超时时长
        readTimeout: 1000
#关闭hystrix超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          #是否开启超时限制,默认是true
#          enabled: false

#设置hystrix超时时长,默认超时时长是1秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
