spring:
  application:
    name: product-service
server:
  port: ${port:9001}
eureka:
  #Eureka客户端配置
  client:
    service-url:
      #Eureka服务地址,如果是集群的话,需要指定其他集群Eureka服务地址
      defaultZone: ${defaultZone:http://${eureka.instance.ip-address}:8001/eureka}
      #Eureka服务地址,如果是集群的话,需要指定其他集群Eureka服务地址(服务器地址)
      defaultZone: ${defaultZone:http://117.78.17.127:8001/eureka}
    #是否注册到Eureka注册中心
    register-with-eureka: true
    #是否拉取服务列表
    fetch-registry: false
  #实例配置
  instance:
    #Eureka客户端实例ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #更倾向于使用IP地址,而不是域名
    prefer-ip-address: true
    #本地IP地址
    #ip-address: 127.0.0.1
    #服务器IP地址
    ip-address: 117.78.17.127
    #服务续约时间,默认值30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效时间,默认值90秒
    lease-expiration-duration-in-seconds: 90
world: world
